[ADD] pg catalog with idle killer
ingadhoc/rancher-catalog pull request #7
Opened 2020-08-12 03:31 UTC by jjscarafia

2020-08-12 03:45 UTC, jjscarafia commented
@ivantodorovich con este nuevo catalogo levantamos un container al costado para que cada un tiempo ate las conexiones iddle, esto es porque en pg 11, 12 no está más "cron" y este fue el approach más simple que se nos ocurrio
NOTA: yo personalmente no voy a acutalizar los postgres 9.6 a esta nueva versión de catálogo y los voy a dejar como estar, este catalogo nuevo lo estoy usando con los pg 12 que estoy usando en v13

2020-08-12 09:04 UTC, ivantodorovich requested changes
Buenas Juan! 

Buenísimo. Dejo algunos comentarios entre líneas.

2020-08-12 09:04 UTC, ivantodorovich commented on templates/adhoc-postgres/5/docker-compose.yml
> +    - '5435'
Este port no debería venir de un answer?

2020-08-12 09:04 UTC, ivantodorovich commented on templates/adhoc-postgres/5/docker-compose.yml
> +    - odoo
Lo mismo acá, no debería ser el postgres_user?

2020-08-12 09:04 UTC, ivantodorovich commented on templates/adhoc-postgres/5/docker-compose.yml
> +    - postgres
postgres_db?
.
Sino, creo que sería mejor setear las variables de entorno, usando los answer del catalogo:
PGDATABASE (reemplaza -d)
PGHOST (reemplaza -h)
PGPORT (-p)
PGUSER (-U)

Y de esa manera el entry queda simplemente psql -c SQL

2020-08-13 00:52 UTC, jjscarafia commented on templates/adhoc-postgres/5/docker-compose.yml
> +    - postgres
juju, mala mía, bien ahí con el review y la sugerencia. 
Agregué tmb esas en vars al postgres en si para que para tareas de maintenance o lo que sea se pueda entrar con psql, te parece bien? Si no lo sacamos, no tengo drama.

2020-08-13 07:21 UTC, ivantodorovich approved these changes
10 puntos! 👌🏻

2020-08-13 14:30 UTC, merged